from sqlalchemy import Column, Float, ForeignKey, String
from sqlalchemy.orm import relationship

from aana.configs.db import IdSqlType, id_type
from aana.models.db.base import BaseModel, TimeStampEntity


class Transcript(BaseModel, TimeStampEntity):
    """ORM class for media transcripts generated by a model."""

    __tablename__ = "transcripts"

    id = Column(IdSqlType, primary_key=True)  # noqa: A003
    model = Column(String, comment="Name of model used to generate transcript")
    media_id = Column(
        IdSqlType, ForeignKey("media.id"), comment="Foreign key to media table"
    )
    transcript = Column(String, comment="Full text transcript of media")
    segments = Column(String, comment="Segments of the transcript")
    language = Column(
        String, comment="Language of the transcript as predicted by model"
    )
    language_confidence = Column(
        Float, comment="Confidence score of language prediction"
    )

    media = relationship("Media", back_populates="transcripts")
