from __future__ import annotations  # Let classes use themselves in type annotations

from typing import TYPE_CHECKING

from sqlalchemy import JSON, CheckConstraint, Column, Float, ForeignKey, Integer, String
from sqlalchemy.orm import relationship

from aana.configs.db import MediaIdSqlType
from aana.models.db.base import BaseEntity, TimeStampEntity

if TYPE_CHECKING:
    from aana.models.pydantic.asr_output import (
        AsrSegments,
        AsrTranscription,
        AsrTranscriptionInfo,
    )
    from aana.models.pydantic.media_id import MediaId


class TranscriptEntity(BaseEntity, TimeStampEntity):
    """ORM class for media transcripts generated by a model."""

    __tablename__ = "transcripts"

    id = Column(Integer, autoincrement=True, primary_key=True)  # noqa A003
    model = Column(
        String, nullable=False, comment="Name of model used to generate transcript"
    )
    media_id = Column(
        MediaIdSqlType,
        ForeignKey("media.id"),
        nullable=False,
        comment="Foreign key to media table",
    )
    video_id = Column(
        Integer,
        ForeignKey("video.id"),
        nullable=False,
        comment="Foreign key to video table",
    )
    transcript = Column(String, comment="Full text transcript of media")
    segments = Column(JSON, comment="Segments of the transcript")
    language = Column(
        String, comment="Language of the transcript as predicted by model"
    )
    language_confidence = Column(
        Float,
        CheckConstraint("0 <= language_confidence <= 1"),
        comment="Confidence score of language prediction",
    )

    video = relationship("VideoEntity", back_populates="transcripts")

    @classmethod
    def from_asr_output(
        cls,
        model_name: str,
        media_id: MediaId,
        video_id: int,
        info: AsrTranscriptionInfo,
        transcription: AsrTranscription,
        segments: AsrSegments,
    ) -> TranscriptEntity:
        """Converts an AsrTranscriptionInfo and AsrTranscription to a single Transcript entity."""
        return TranscriptEntity(
            model=model_name,
            media_id=media_id,
            video_id=video_id,
            language=info.language,
            language_confidence=info.language_confidence,
            transcript=transcription.text,
            segments=[s.model_dump() for s in segments],
        )
