"""Name constraints, fix cascading deletes.

Revision ID: 0918cb09ac67
Revises: 86a31568e6c2
Create Date: 2024-03-07 12:56:36.129852

"""
from collections.abc import Sequence

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "0918cb09ac67"
down_revision: str | None = "86a31568e6c2"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade database to this revision from previous."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("media", schema=None) as batch_op:
        batch_op.drop_constraint("fk_media_video_id_video", type_="foreignkey")
        batch_op.create_foreign_key(
            batch_op.f("fk_media_video_id_video"),
            "video",
            ["video_id"],
            ["id"],
            ondelete="CASCADE",
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade database from this revision to previous."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("media", schema=None) as batch_op:
        batch_op.drop_constraint(
            batch_op.f("fk_media_video_id_video"), type_="foreignkey"
        )
        batch_op.create_foreign_key(
            "fk_media_video_id_video", "video", ["video_id"], ["id"]
        )

    # ### end Alembic commands ###
