"""Added video title and description

Revision ID: 86a31568e6c2
Revises: b5a993b53e6c
Create Date: 2024-01-18 15:06:41.130502

"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = '86a31568e6c2'
down_revision: str | None = 'b5a993b53e6c'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade database to this revision from previous."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('video', sa.Column('title', sa.String(), nullable=True, comment='Title of the video'))
    op.add_column('video', sa.Column('description', sa.String(), nullable=True, comment='Description of the video'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade database from this revision to previous."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('video', 'description')
    op.drop_column('video', 'title')
    # ### end Alembic commands ###
