"""Add num_retries to tasks.

Revision ID: 917ef6ad672e
Revises: b9860676dd49
Create Date: 2024-08-23 10:00:55.579226

"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "917ef6ad672e"
down_revision: str | None = "b9860676dd49"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade database to this revision from previous."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("tasks", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column(
                "num_retries",
                sa.Integer(),
                nullable=False,
                comment="Number of retries",
                server_default=sa.text("0"),
            )
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade database from this revision to previous."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("tasks", schema=None) as batch_op:
        batch_op.drop_column("num_retries")

    # ### end Alembic commands ###
