"""init

Revision ID: b77fb9a2c1f4
Revises: 
Create Date: 2024-07-16 10:14:08.164000

"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "b77fb9a2c1f4"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade database to this revision from previous."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "media",
        sa.Column(
            "id",
            sa.String(length=36),
            nullable=False,
            comment="Unique identifier for the media",
        ),
        sa.Column(
            "media_type", sa.String(), nullable=False, comment="The type of media"
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
            comment="Timestamp when row is inserted",
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
            comment="Timestamp when row is updated",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_media")),
    )
    op.create_table(
        "tasks",
        sa.Column("id", sa.UUID(), nullable=False, comment="Task ID"),
        sa.Column(
            "endpoint",
            sa.String(),
            nullable=False,
            comment="The endpoint to which the task is assigned",
        ),
        sa.Column("data", sa.PickleType(), nullable=False, comment="Data for the task"),
        sa.Column(
            "status",
            sa.Enum(
                "CREATED",
                "ASSIGNED",
                "COMPLETED",
                "RUNNING",
                "FAILED",
                "NOT_FINISHED",
                name="status",
            ),
            nullable=False,
            comment="Status of the task",
        ),
        sa.Column(
            "priority",
            sa.Integer(),
            nullable=False,
            comment="Priority of the task (0 is the lowest)",
        ),
        sa.Column(
            "assigned_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=True,
            comment="Timestamp when the task was assigned",
        ),
        sa.Column(
            "completed_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=True,
            comment="Timestamp when the task was completed",
        ),
        sa.Column(
            "progress",
            sa.Float(),
            nullable=False,
            comment="Progress of the task in percentage",
        ),
        sa.Column(
            "result",
            sa.JSON(),
            nullable=True,
            comment="Result of the task in JSON format",
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
            comment="Timestamp when row is inserted",
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
            comment="Timestamp when row is updated",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_tasks")),
    )
    op.create_table(
        "video",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("path", sa.String(), nullable=True, comment="Path"),
        sa.Column("url", sa.String(), nullable=True, comment="URL"),
        sa.Column("title", sa.String(), nullable=True, comment="Title"),
        sa.Column("description", sa.String(), nullable=True, comment="Description"),
        sa.ForeignKeyConstraint(["id"], ["media.id"], name=op.f("fk_video_id_media")),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_video")),
    )
    op.create_table(
        "extended_video",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column(
            "duration", sa.Float(), nullable=False, comment="Video duration in seconds"
        ),
        sa.Column(
            "status",
            sa.Enum(
                "CREATED",
                "RUNNING",
                "COMPLETED",
                "FAILED",
                name="videoprocessingstatus",
            ),
            nullable=False,
            comment="Processing status",
        ),
        sa.ForeignKeyConstraint(
            ["id"], ["video.id"], name=op.f("fk_extended_video_id_video")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_extended_video")),
    )
    op.create_table(
        "captions",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column(
            "model",
            sa.String(),
            nullable=False,
            comment="Name of model used to generate the caption",
        ),
        sa.Column(
            "media_id",
            sa.String(length=36),
            nullable=False,
            comment="Foreign key to video table",
        ),
        sa.Column(
            "frame_id",
            sa.Integer(),
            nullable=False,
            comment="The 0-based frame id of video for caption",
        ),
        sa.Column("caption", sa.String(), nullable=False, comment="Frame caption"),
        sa.Column(
            "timestamp",
            sa.Float(),
            nullable=False,
            comment="Frame timestamp in seconds",
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
            comment="Timestamp when row is inserted",
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
            comment="Timestamp when row is updated",
        ),
        sa.ForeignKeyConstraint(
            ["media_id"],
            ["extended_video.id"],
            name=op.f("fk_captions_media_id_extended_video"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_captions")),
    )
    op.create_table(
        "transcripts",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column(
            "model",
            sa.String(),
            nullable=False,
            comment="Name of model used to generate transcript",
        ),
        sa.Column(
            "media_id",
            sa.String(length=36),
            nullable=False,
            comment="Foreign key to video table",
        ),
        sa.Column(
            "transcript",
            sa.String(),
            nullable=False,
            comment="Full text transcript of media",
        ),
        sa.Column(
            "segments", sa.JSON(), nullable=False, comment="Segments of the transcript"
        ),
        sa.Column(
            "language",
            sa.String(),
            nullable=False,
            comment="Language of the transcript as predicted by model",
        ),
        sa.Column(
            "language_confidence",
            sa.Float(),
            nullable=False,
            comment="Confidence score of language prediction",
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
            comment="Timestamp when row is inserted",
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
            comment="Timestamp when row is updated",
        ),
        sa.ForeignKeyConstraint(
            ["media_id"],
            ["extended_video.id"],
            name=op.f("fk_transcripts_media_id_extended_video"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_transcripts")),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade database from this revision to previous."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("transcripts")
    op.drop_table("captions")
    op.drop_table("extended_video")
    op.drop_table("video")
    op.drop_table("tasks")
    op.drop_table("media")
    # ### end Alembic commands ###
