"""Initialize.

Revision ID: d63d3838d344
Revises: 
Create Date: 2023-12-07 11:58:35.095546

"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'd63d3838d344'
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade database to this revision from previous."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('media',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('duration', sa.Float(), nullable=True, comment='Media duration in seconds'),
    sa.Column('media_type', sa.String(), nullable=True, comment='Media type'),
    sa.Column('orig_filename', sa.String(), nullable=True, comment='Original filename'),
    sa.Column('orig_url', sa.String(), nullable=True, comment='Original URL'),
    sa.Column('create_ts', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True, comment='Timestamp when row is inserted'),
    sa.Column('update_ts', sa.DateTime(timezone=True), nullable=True, comment='Timestamp when row is updated'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('captions',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('model', sa.String(), nullable=True, comment='Name of model used to generate the caption'),
    sa.Column('media_id', sa.String(), nullable=True, comment='Foreign key to media table'),
    sa.Column('frame_id', sa.Integer(), nullable=True, comment='The 0-based frame id of media for caption'),
    sa.Column('caption', sa.String(), nullable=True, comment='Frame caption'),
    sa.Column('timestamp', sa.Float(), nullable=True, comment='Frame timestamp in seconds'),
    sa.Column('create_ts', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True, comment='Timestamp when row is inserted'),
    sa.Column('update_ts', sa.DateTime(timezone=True), nullable=True, comment='Timestamp when row is updated'),
    sa.ForeignKeyConstraint(['media_id'], ['media.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('transcripts',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('model', sa.String(), nullable=True, comment='Name of model used to generate transcript'),
    sa.Column('media_id', sa.String(), nullable=True, comment='Foreign key to media table'),
    sa.Column('transcript', sa.String(), nullable=True, comment='Full text transcript of media'),
    sa.Column('segments', sa.String(), nullable=True, comment='Segments of the transcript'),
    sa.Column('language', sa.String(), nullable=True, comment='Language of the transcript as predicted by model'),
    sa.Column('language_confidence', sa.Float(), nullable=True, comment='Confidence score of language prediction'),
    sa.Column('create_ts', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True, comment='Timestamp when row is inserted'),
    sa.Column('update_ts', sa.DateTime(timezone=True), nullable=True, comment='Timestamp when row is updated'),
    sa.ForeignKeyConstraint(['media_id'], ['media.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade database from this revision to previous."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('transcripts')
    op.drop_table('captions')
    op.drop_table('media')
    # ### end Alembic commands ###
