name: Publish Python Package

on:
  release:
    types: [published]
  workflow_dispatch:
    inputs:
      publish_target:
        description: 'Select the target PyPI repository'
        required: true
        default: 'testpypi'
        type: choice
        options:
          - pypi
          - testpypi

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python 3.10
      uses: actions/setup-python@v5
      with:
        python-version: "3.10"

    - name: Bootstrap uv
      uses: astral-sh/setup-uv@v5
      with:
        version: "0.8.4"

    - name: Install dependencies
      run: uv sync

    - name: Build the package
      run: uv build

    - name: Publish to PyPI
      if: github.event_name == 'release' || (github.event_name == 'workflow_dispatch' && github.event.inputs.publish_target == 'pypi')
      env:
        UV_PUBLISH_USERNAME: "__token__"
        UV_PUBLISH_PASSWORD: ${{ secrets.PYPI_API_TOKEN }}
      run: |
        uv publish

    - name: Publish to Test PyPI
      if: github.event_name == 'workflow_dispatch' && github.event.inputs.publish_target == 'testpypi'
      env:
        UV_PUBLISH_USERNAME: "__token__"
        UV_PUBLISH_PASSWORD: ${{ secrets.TEST_PYPI_API_TOKEN }}
      run: |
        uv publish --publish-url https://test.pypi.org/legacy/
