# This workflow will install Python dependencies, run tests and lint with a variety of Python versions
# For more information see: https://docs.github.com/en/ actions/automating-builds-and-tests/building-and-testing-python

name: Python package

on:
  push:
    branches:
      - '**'  # Runs on push to any branch
  pull_request:
    branches:
      - '**'  # Runs on pull requests to any branch
  workflow_dispatch:  # Allows for manual triggering

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.10"]

    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    - name: Bootstrap poetry
      run: |
        curl -sSL https://install.python-poetry.org | python - -y
    - name: Update PATH
      run: echo "$HOME/.local/bin" >> $GITHUB_PATH
    - name: Install dependencies
      run: |
        poetry install
        sudo apt-get update
        sudo apt-get install ffmpeg
    - name: Test with pytest
      run: poetry run pytest -vv
